import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Boxes,ClipboardCheck,Building2,Wrench,Search,Plus,Download,Menu,CheckCircle2,AlertTriangle,Laptop,Monitor,ScanLine,Package,ArrowRight,CalendarDays,X,ChevronRight}from'lucide-react';
import './style.css';
const seed=[
{id:'DT-1001',name:'Dell Latitude 5440',type:'Laptop',serial:'DL5440-9921',building:'Building A',location:'IT Storage',status:'Available',audit:'Verified'},
{id:'DT-1002',name:'Zebra DS3678',type:'Scanner',serial:'ZB-3678-112',building:'Building A',location:'Station 214-02',status:'Deployed',audit:'Verified'},
{id:'DT-1003',name:'HP EliteDesk 800',type:'Desktop',serial:'HP800-4218',building:'Building A',location:'Station 214-02',status:'Deployed',audit:'Pending'},
{id:'DT-1004',name:'Dell P2422H',type:'Monitor',serial:'DP24-9922',building:'Building A',location:'Station 214-02',status:'Deployed',audit:'Verified'},
{id:'DT-1005',name:'Honeywell 1950g',type:'Scanner',serial:'HW-1950-555',building:'Building B',location:'Station 4151',status:'Maintenance',audit:'Missing'},
{id:'DT-1006',name:'Lenovo ThinkPad T14',type:'Laptop',serial:'LT14-2180',building:'Building B',location:'Loaner Storage',status:'Available',audit:'Pending'},
{id:'DT-1007',name:'Logitech C920',type:'Accessory',serial:'LC920-001',building:'Building A',location:'Station 214-02',status:'Deployed',audit:'Verified'},
{id:'DT-1008',name:'Zebra TC52',type:'Scanner',serial:'TC52-8290',building:'Building B',location:'Station 4151',status:'Deployed',audit:'Pending'}
];
const nav=[['Dashboard',LayoutDashboard],['Inventory',Boxes],['Audits',ClipboardCheck],['Buildings',Building2],['Maintenance',Wrench]];
function App(){
const[page,setPage]=useState('Dashboard'),[assets,setAssets]=useState(()=>{try{return JSON.parse(localStorage.getItem('dt-assets'))||seed}catch{return seed}}),[query,setQuery]=useState(''),[showAdd,setShowAdd]=useState(false),[menu,setMenu]=useState(false),[auditPeriod,setAuditPeriod]=useState('Weekly'),[verified,setVerified]=useState(()=>{try{return JSON.parse(localStorage.getItem('dt-verified'))||{Weekly:[],Monthly:[]}}catch{return{Weekly:[],Monthly:[]}}}),[form,setForm]=useState({name:'',type:'Laptop',serial:'',building:'Building A',location:'',status:'Available'});
const saveAssets=(next)=>{setAssets(next);localStorage.setItem('dt-assets',JSON.stringify(next))};
const filtered=useMemo(()=>assets.filter(a=>[a.id,a.name,a.serial,a.type,a.building,a.location,a.status].some(v=>v.toLowerCase().includes(query.toLowerCase()))),[assets,query]);
const count=(status)=>assets.filter(a=>a.status===status).length;
const auditCount=verified[auditPeriod]?.length||0;
function addAsset(e){e.preventDefault();if(!form.name.trim()||!form.serial.trim())return;if(assets.some(a=>a.serial.toLowerCase()===form.serial.trim().toLowerCase())){alert('Serial number already exists');return}const id='DT-'+String(Math.max(1000,...assets.map(a=>Number(a.id.replace('DT-',''))||1000))+1);saveAssets([{...form,id,name:form.name.trim(),serial:form.serial.trim(),audit:'Pending'},...assets]);setShowAdd(false);setForm({name:'',type:'Laptop',serial:'',building:'Building A',location:'',status:'Available'});setPage('Inventory')}
function verify(id){const next={...verified,[auditPeriod]:verified[auditPeriod].includes(id)?verified[auditPeriod].filter(x=>x!==id):[...verified[auditPeriod],id]};setVerified(next);localStorage.setItem('dt-verified',JSON.stringify(next))}
function exportCSV(){const cols=['id','name','type','serial','building','location','status','audit'];const csv=[cols.join(','),...filtered.map(a=>cols.map(k=>'"'+String(a[k]||'').replaceAll('"','""')+'"').join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const el=document.createElement('a');el.href=url;el.download='devicetrustline-assets.csv';el.click();URL.revokeObjectURL(url)}
const metrics=[{label:'Total Assets',value:assets.length,icon:Boxes,sub:'Across all buildings'},{label:'Deployed',value:count('Deployed'),icon:Monitor,sub:'Active equipment'},{label:'Available',value:count('Available'),icon:CheckCircle2,sub:'Ready for assignment'},{label:'Needs Attention',value:count('Maintenance')+assets.filter(a=>a.audit==='Missing').length,icon:AlertTriangle,sub:'Maintenance / missing'}];
return <div className="shell"><aside className={'sidebar '+(menu?'open':'')}><div className="brand"><div className="brand-icon"><ScanLine size={22}/></div><div><strong>DeviceTrustline</strong><small>ASSET INTELLIGENCE</small></div></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([name,Icon])=><button key={name} className={'nav-item '+(page===name?'active':'')} onClick={()=>{setPage(name);setMenu(false);setQuery('')}}><Icon size={19}/>{name}{page===name&&<ChevronRight size={15} className="nav-chevron"/>}</button>)}</nav><div className="sidebar-bottom"><div className="workspace-avatar">DT</div><div><strong>Demo Workspace</strong><small>Frontend MVP</small></div></div></aside><div className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu"><Menu size={22}/></button><div className="breadcrumb">Workspace <ChevronRight size={15}/> <strong>{page}</strong></div><div className="top-right"><span className="demo-pill">● Demo mode</span><span className="avatar">DT</span></div></header><main className="content"><div className="heading"><div><div className="eyebrow">DEVICE TRUSTLINE / {page.toUpperCase()}</div><h1>{page==='Dashboard'?'Asset Overview':page}</h1><p>{page==='Dashboard'?'Your equipment, locations and audit activity in one place.':page==='Inventory'?'Search and manage every asset across your facilities.':page==='Audits'?'Track physical verification for weekly and monthly inventory reviews.':page==='Buildings'?'A clear view of your equipment by facility.':'Keep track of devices requiring maintenance.'}</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add Asset</button></div>
{page==='Dashboard'&&<><div className="metrics">{metrics.map(({label,value,icon:Icon,sub})=><div className="metric" key={label}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon size={19}/></span></div><strong>{value}</strong><small>{sub}</small></div>)}</div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Inventory by Type</h2><p>Distribution across your portfolio</p></div></div><div className="type-list">{['Laptop','Desktop','Scanner','Monitor','Accessory'].map(t=>{const n=assets.filter(a=>a.type===t).length;return <div className="type-row" key={t}><div><span>{t}</span><b>{n}</b></div><div className="track"><div style={{width:(assets.length?n/assets.length*100:0)+'%'}}/></div></div>})}</div></section><section className="panel"><div className="panel-head"><div><h2>Audit Snapshot</h2><p>Current demo verification progress</p></div><CalendarDays size={20}/></div>{['Weekly','Monthly'].map(p=><div className="audit-snapshot" key={p}><div><strong>{p} Audit</strong><small>{(verified[p]||[]).length} of {assets.length} checked</small></div><div className="progress-track"><div style={{width:(assets.length?(verified[p]||[]).length/assets.length*100:0)+'%'}}/></div></div>)}<button className="text-link" onClick={()=>setPage('Audits')}>Open Audit Center <ArrowRight size={16}/></button></section></div><section className="panel"><div className="panel-head"><div><h2>Recent Inventory</h2><p>Latest registered equipment</p></div><button className="outline" onClick={()=>setPage('Inventory')}>View all <ArrowRight size={15}/></button></div><AssetTable assets={assets.slice(0,5)}/></section></>}
{page==='Inventory'&&<section className="panel"><div className="panel-head wrap"><div><h2>All Assets <span className="count">{filtered.length}</span></h2><p>Inventory registry</p></div><button className="outline" onClick={exportCSV}><Download size={16}/> Export CSV</button></div><div className="search"><Search size={18}/><input placeholder="Search assets, serials, locations..." value={query} onChange={e=>setQuery(e.target.value)}/></div><AssetTable assets={filtered}/></section>}
{page==='Audits'&&<><div className="tabs">{['Weekly','Monthly'].map(p=><button key={p} className={auditPeriod===p?'selected':''} onClick={()=>setAuditPeriod(p)}>{p} Audit</button>)}</div><div className="metrics audit-metrics"><div className="metric"><span>Expected Assets</span><strong>{assets.length}</strong><small>Demo inventory snapshot</small></div><div className="metric"><span>Verified</span><strong>{auditCount}</strong><small>{auditPeriod} cycle</small></div><div className="metric"><span>Remaining</span><strong>{assets.length-auditCount}</strong><small>Pending verification</small></div></div><section className="panel"><div className="panel-head"><div><h2>{auditPeriod} Verification Checklist</h2><p>Demo only — selections are stored in this browser, not a formal audit record.</p></div></div><div className="audit-items">{assets.map(a=><div className="audit-item" key={a.id}><div className="asset-square"><Package size={19}/></div><div className="audit-info"><strong>{a.name}</strong><small>{a.id} · {a.building} · {a.location}</small></div><button className={verified[auditPeriod].includes(a.id)?'verified-btn':'outline'} onClick={()=>verify(a.id)}>{verified[auditPeriod].includes(a.id)?<><CheckCircle2 size={16}/> Verified</>:<><ScanLine size={16}/> Mark Verified</>}</button></div>)}</div></section></>}
{page==='Buildings'&&<div className="building-grid">{['Building A','Building B'].map(b=><section className="panel building" key={b}><div className="building-icon"><Building2 size={24}/></div><h2>{b}</h2><p>Equipment and workstation inventory</p><strong>{assets.filter(a=>a.building===b).length} assets</strong><div className="location-list">{[...new Set(assets.filter(a=>a.building===b).map(a=>a.location))].map(l=><div key={l}><span>{l||'Unassigned'}</span><b>{assets.filter(a=>a.building===b&&a.location===l).length}</b></div>)}</div></section>)}</div>}
{page==='Maintenance'&&<section className="panel"><div className="panel-head"><div><h2>Maintenance Queue</h2><p>Assets currently marked for repair or investigation</p></div></div><AssetTable assets={assets.filter(a=>a.status==='Maintenance'||a.audit==='Missing')}/></section>}
</main></div>{showAdd&&<div className="modal-backdrop" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-title"><div><h2>Register New Asset</h2><p>Add equipment to your inventory</p></div><button className="icon-btn" onClick={()=>setShowAdd(false)} aria-label="Close"><X/></button></div><form onSubmit={addAsset}><div className="form-grid">{[['name','Asset Name'],['serial','Serial Number'],['location','Location / Station']].map(([key,label])=><label key={key}>{label}<input required={key!=='location'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label}/></label>)}{[['type','Asset Type',['Laptop','Desktop','Scanner','Monitor','Accessory','Printer','Other']],['building','Building',['Building A','Building B']],['status','Status',['Available','Deployed','Maintenance','Retired']]].map(([key,label,opts])=><label key={key}>{label}<select value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}>{opts.map(x=><option key={x}>{x}</option>)}</select></label>)}</div><div className="modal-actions"><button type="button" className="outline" onClick={()=>setShowAdd(false)}>Cancel</button><button type="submit" className="primary"><Plus size={16}/> Register Asset</button></div></form></div></div>}</div>}
function AssetTable({assets}){return <div className="table-scroll"><table><thead><tr><th>ASSET</th><th>TYPE</th><th>SERIAL NUMBER</th><th>LOCATION</th><th>STATUS</th></tr></thead><tbody>{assets.length===0?<tr><td colSpan="5" className="empty">No assets found</td></tr>:assets.map(a=><tr key={a.id}><td><div className="asset-name"><span className="asset-square">{a.type==='Laptop'?<Laptop size={18}/>:a.type==='Desktop'?<Monitor size={18}/>:<Package size={18}/>}</span><span><strong>{a.name}</strong><small>{a.id}</small></span></div></td><td>{a.type}</td><td className="mono">{a.serial}</td><td><strong className="normal">{a.building}</strong><small>{a.location||'Unassigned'}</small></td><td><span className={'status '+a.status.toLowerCase()}><i/>{a.status}</span></td></tr>)}</tbody></table></div>}
createRoot(document.getElementById('root')).render(<App/>);
